server:
  # 端口
  port: 2020
spring:
  application:
    name: fenzsen_blog_system
  # 数据库相关
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    timeout: 5000

logging:
  level:
    #不同目录下的日志可配置不同级别
    org.springfromework.web: INFO
    org.hibernate: ERROR
  #采用相对路径方式将日志文件输出到【log/myspringboot.log】
  file:
    path: log/myspringboot.log